/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasscRouteImport } from './routes/vendassc'
import { Route as PromosombraRouteImport } from './routes/promosombra'
import { Route as PromociliusRouteImport } from './routes/promocilius'
import { Route as PromoccRouteImport } from './routes/promocc'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as MeusCertificadosRouteImport } from './routes/meus-certificados'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as CertificadoRouteImport } from './routes/certificado'
import { Route as CentraladminRouteImport } from './routes/centraladmin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CursoSlugRouteImport } from './routes/curso.$slug'
import { Route as AdminTemplateRouteImport } from './routes/admin.template'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminModulesRouteImport } from './routes/admin.modules'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminCertificadosRouteImport } from './routes/admin.certificados'
import { Route as ApiPublicKiwifyWebhookRouteImport } from './routes/api/public/kiwify-webhook'
import { Route as ApiPublicInfinitepayWebhookRouteImport } from './routes/api/public/infinitepay-webhook'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files/$'
import { Route as ApiAdminCourseCoverRouteImport } from './routes/api/admin/course-cover'
import { Route as ApiAdminCourseAssetRouteImport } from './routes/api/admin/course-asset'

const VendasscRoute = VendasscRouteImport.update({
  id: '/vendassc',
  path: '/vendassc',
  getParentRoute: () => rootRouteImport,
} as any)
const PromosombraRoute = PromosombraRouteImport.update({
  id: '/promosombra',
  path: '/promosombra',
  getParentRoute: () => rootRouteImport,
} as any)
const PromociliusRoute = PromociliusRouteImport.update({
  id: '/promocilius',
  path: '/promocilius',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoccRoute = PromoccRouteImport.update({
  id: '/promocc',
  path: '/promocc',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusCertificadosRoute = MeusCertificadosRouteImport.update({
  id: '/meus-certificados',
  path: '/meus-certificados',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadoRoute = CertificadoRouteImport.update({
  id: '/certificado',
  path: '/certificado',
  getParentRoute: () => rootRouteImport,
} as any)
const CentraladminRoute = CentraladminRouteImport.update({
  id: '/centraladmin',
  path: '/centraladmin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursoSlugRoute = CursoSlugRouteImport.update({
  id: '/curso/$slug',
  path: '/curso/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplateRoute = AdminTemplateRouteImport.update({
  id: '/admin/template',
  path: '/admin/template',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/admin/modules',
  path: '/admin/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCertificadosRoute = AdminCertificadosRouteImport.update({
  id: '/admin/certificados',
  path: '/admin/certificados',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKiwifyWebhookRoute = ApiPublicKiwifyWebhookRouteImport.update({
  id: '/api/public/kiwify-webhook',
  path: '/api/public/kiwify-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInfinitepayWebhookRoute =
  ApiPublicInfinitepayWebhookRouteImport.update({
    id: '/api/public/infinitepay-webhook',
    path: '/api/public/infinitepay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCourseCoverRoute = ApiAdminCourseCoverRouteImport.update({
  id: '/api/admin/course-cover',
  path: '/api/admin/course-cover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCourseAssetRoute = ApiAdminCourseAssetRouteImport.update({
  id: '/api/admin/course-asset',
  path: '/api/admin/course-asset',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/centraladmin': typeof CentraladminRoute
  '/certificado': typeof CertificadoRoute
  '/cursos': typeof CursosRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/meus-certificados': typeof MeusCertificadosRoute
  '/obrigado': typeof ObrigadoRoute
  '/promocc': typeof PromoccRoute
  '/promocilius': typeof PromociliusRoute
  '/promosombra': typeof PromosombraRoute
  '/vendassc': typeof VendasscRoute
  '/admin/certificados': typeof AdminCertificadosRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/template': typeof AdminTemplateRoute
  '/curso/$slug': typeof CursoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/course-asset': typeof ApiAdminCourseAssetRoute
  '/api/admin/course-cover': typeof ApiAdminCourseCoverRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/public/infinitepay-webhook': typeof ApiPublicInfinitepayWebhookRoute
  '/api/public/kiwify-webhook': typeof ApiPublicKiwifyWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/centraladmin': typeof CentraladminRoute
  '/certificado': typeof CertificadoRoute
  '/cursos': typeof CursosRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/meus-certificados': typeof MeusCertificadosRoute
  '/obrigado': typeof ObrigadoRoute
  '/promocc': typeof PromoccRoute
  '/promocilius': typeof PromociliusRoute
  '/promosombra': typeof PromosombraRoute
  '/vendassc': typeof VendasscRoute
  '/admin/certificados': typeof AdminCertificadosRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/template': typeof AdminTemplateRoute
  '/curso/$slug': typeof CursoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/course-asset': typeof ApiAdminCourseAssetRoute
  '/api/admin/course-cover': typeof ApiAdminCourseCoverRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/public/infinitepay-webhook': typeof ApiPublicInfinitepayWebhookRoute
  '/api/public/kiwify-webhook': typeof ApiPublicKiwifyWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/centraladmin': typeof CentraladminRoute
  '/certificado': typeof CertificadoRoute
  '/cursos': typeof CursosRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/meus-certificados': typeof MeusCertificadosRoute
  '/obrigado': typeof ObrigadoRoute
  '/promocc': typeof PromoccRoute
  '/promocilius': typeof PromociliusRoute
  '/promosombra': typeof PromosombraRoute
  '/vendassc': typeof VendasscRoute
  '/admin/certificados': typeof AdminCertificadosRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/template': typeof AdminTemplateRoute
  '/curso/$slug': typeof CursoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/course-asset': typeof ApiAdminCourseAssetRoute
  '/api/admin/course-cover': typeof ApiAdminCourseCoverRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/public/infinitepay-webhook': typeof ApiPublicInfinitepayWebhookRoute
  '/api/public/kiwify-webhook': typeof ApiPublicKiwifyWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/centraladmin'
    | '/certificado'
    | '/cursos'
    | '/inicio'
    | '/login'
    | '/meus-certificados'
    | '/obrigado'
    | '/promocc'
    | '/promocilius'
    | '/promosombra'
    | '/vendassc'
    | '/admin/certificados'
    | '/admin/courses'
    | '/admin/login'
    | '/admin/modules'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/template'
    | '/curso/$slug'
    | '/admin/'
    | '/api/admin/course-asset'
    | '/api/admin/course-cover'
    | '/api/files/$'
    | '/api/public/infinitepay-webhook'
    | '/api/public/kiwify-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/centraladmin'
    | '/certificado'
    | '/cursos'
    | '/inicio'
    | '/login'
    | '/meus-certificados'
    | '/obrigado'
    | '/promocc'
    | '/promocilius'
    | '/promosombra'
    | '/vendassc'
    | '/admin/certificados'
    | '/admin/courses'
    | '/admin/login'
    | '/admin/modules'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/template'
    | '/curso/$slug'
    | '/admin'
    | '/api/admin/course-asset'
    | '/api/admin/course-cover'
    | '/api/files/$'
    | '/api/public/infinitepay-webhook'
    | '/api/public/kiwify-webhook'
  id:
    | '__root__'
    | '/'
    | '/centraladmin'
    | '/certificado'
    | '/cursos'
    | '/inicio'
    | '/login'
    | '/meus-certificados'
    | '/obrigado'
    | '/promocc'
    | '/promocilius'
    | '/promosombra'
    | '/vendassc'
    | '/admin/certificados'
    | '/admin/courses'
    | '/admin/login'
    | '/admin/modules'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/template'
    | '/curso/$slug'
    | '/admin/'
    | '/api/admin/course-asset'
    | '/api/admin/course-cover'
    | '/api/files/$'
    | '/api/public/infinitepay-webhook'
    | '/api/public/kiwify-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CentraladminRoute: typeof CentraladminRoute
  CertificadoRoute: typeof CertificadoRoute
  CursosRoute: typeof CursosRoute
  InicioRoute: typeof InicioRoute
  LoginRoute: typeof LoginRoute
  MeusCertificadosRoute: typeof MeusCertificadosRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PromoccRoute: typeof PromoccRoute
  PromociliusRoute: typeof PromociliusRoute
  PromosombraRoute: typeof PromosombraRoute
  VendasscRoute: typeof VendasscRoute
  AdminCertificadosRoute: typeof AdminCertificadosRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminModulesRoute: typeof AdminModulesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTemplateRoute: typeof AdminTemplateRoute
  CursoSlugRoute: typeof CursoSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAdminCourseAssetRoute: typeof ApiAdminCourseAssetRoute
  ApiAdminCourseCoverRoute: typeof ApiAdminCourseCoverRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
  ApiPublicInfinitepayWebhookRoute: typeof ApiPublicInfinitepayWebhookRoute
  ApiPublicKiwifyWebhookRoute: typeof ApiPublicKiwifyWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendassc': {
      id: '/vendassc'
      path: '/vendassc'
      fullPath: '/vendassc'
      preLoaderRoute: typeof VendasscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promosombra': {
      id: '/promosombra'
      path: '/promosombra'
      fullPath: '/promosombra'
      preLoaderRoute: typeof PromosombraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promocilius': {
      id: '/promocilius'
      path: '/promocilius'
      fullPath: '/promocilius'
      preLoaderRoute: typeof PromociliusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promocc': {
      id: '/promocc'
      path: '/promocc'
      fullPath: '/promocc'
      preLoaderRoute: typeof PromoccRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-certificados': {
      id: '/meus-certificados'
      path: '/meus-certificados'
      fullPath: '/meus-certificados'
      preLoaderRoute: typeof MeusCertificadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificado': {
      id: '/certificado'
      path: '/certificado'
      fullPath: '/certificado'
      preLoaderRoute: typeof CertificadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centraladmin': {
      id: '/centraladmin'
      path: '/centraladmin'
      fullPath: '/centraladmin'
      preLoaderRoute: typeof CentraladminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curso/$slug': {
      id: '/curso/$slug'
      path: '/curso/$slug'
      fullPath: '/curso/$slug'
      preLoaderRoute: typeof CursoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/template': {
      id: '/admin/template'
      path: '/admin/template'
      fullPath: '/admin/template'
      preLoaderRoute: typeof AdminTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/admin/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/certificados': {
      id: '/admin/certificados'
      path: '/admin/certificados'
      fullPath: '/admin/certificados'
      preLoaderRoute: typeof AdminCertificadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiwify-webhook': {
      id: '/api/public/kiwify-webhook'
      path: '/api/public/kiwify-webhook'
      fullPath: '/api/public/kiwify-webhook'
      preLoaderRoute: typeof ApiPublicKiwifyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/infinitepay-webhook': {
      id: '/api/public/infinitepay-webhook'
      path: '/api/public/infinitepay-webhook'
      fullPath: '/api/public/infinitepay-webhook'
      preLoaderRoute: typeof ApiPublicInfinitepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/course-cover': {
      id: '/api/admin/course-cover'
      path: '/api/admin/course-cover'
      fullPath: '/api/admin/course-cover'
      preLoaderRoute: typeof ApiAdminCourseCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/course-asset': {
      id: '/api/admin/course-asset'
      path: '/api/admin/course-asset'
      fullPath: '/api/admin/course-asset'
      preLoaderRoute: typeof ApiAdminCourseAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CentraladminRoute: CentraladminRoute,
  CertificadoRoute: CertificadoRoute,
  CursosRoute: CursosRoute,
  InicioRoute: InicioRoute,
  LoginRoute: LoginRoute,
  MeusCertificadosRoute: MeusCertificadosRoute,
  ObrigadoRoute: ObrigadoRoute,
  PromoccRoute: PromoccRoute,
  PromociliusRoute: PromociliusRoute,
  PromosombraRoute: PromosombraRoute,
  VendasscRoute: VendasscRoute,
  AdminCertificadosRoute: AdminCertificadosRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminModulesRoute: AdminModulesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTemplateRoute: AdminTemplateRoute,
  CursoSlugRoute: CursoSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAdminCourseAssetRoute: ApiAdminCourseAssetRoute,
  ApiAdminCourseCoverRoute: ApiAdminCourseCoverRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
  ApiPublicInfinitepayWebhookRoute: ApiPublicInfinitepayWebhookRoute,
  ApiPublicKiwifyWebhookRoute: ApiPublicKiwifyWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
