/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasscRouteImport } from './routes/vendassc'
import { Route as CertificadoRouteImport } from './routes/certificado'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTemplateRouteImport } from './routes/admin.template'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiPublicKiwifyWebhookRouteImport } from './routes/api/public/kiwify-webhook'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files/$'

const VendasscRoute = VendasscRouteImport.update({
  id: '/vendassc',
  path: '/vendassc',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadoRoute = CertificadoRouteImport.update({
  id: '/certificado',
  path: '/certificado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplateRoute = AdminTemplateRouteImport.update({
  id: '/admin/template',
  path: '/admin/template',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKiwifyWebhookRoute = ApiPublicKiwifyWebhookRouteImport.update({
  id: '/api/public/kiwify-webhook',
  path: '/api/public/kiwify-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificado': typeof CertificadoRoute
  '/vendassc': typeof VendasscRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/template': typeof AdminTemplateRoute
  '/admin/': typeof AdminIndexRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/public/kiwify-webhook': typeof ApiPublicKiwifyWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificado': typeof CertificadoRoute
  '/vendassc': typeof VendasscRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/template': typeof AdminTemplateRoute
  '/admin': typeof AdminIndexRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/public/kiwify-webhook': typeof ApiPublicKiwifyWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificado': typeof CertificadoRoute
  '/vendassc': typeof VendasscRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/template': typeof AdminTemplateRoute
  '/admin/': typeof AdminIndexRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/public/kiwify-webhook': typeof ApiPublicKiwifyWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certificado'
    | '/vendassc'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/template'
    | '/admin/'
    | '/api/files/$'
    | '/api/public/kiwify-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificado'
    | '/vendassc'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/template'
    | '/admin'
    | '/api/files/$'
    | '/api/public/kiwify-webhook'
  id:
    | '__root__'
    | '/'
    | '/certificado'
    | '/vendassc'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/template'
    | '/admin/'
    | '/api/files/$'
    | '/api/public/kiwify-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificadoRoute: typeof CertificadoRoute
  VendasscRoute: typeof VendasscRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTemplateRoute: typeof AdminTemplateRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
  ApiPublicKiwifyWebhookRoute: typeof ApiPublicKiwifyWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendassc': {
      id: '/vendassc'
      path: '/vendassc'
      fullPath: '/vendassc'
      preLoaderRoute: typeof VendasscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificado': {
      id: '/certificado'
      path: '/certificado'
      fullPath: '/certificado'
      preLoaderRoute: typeof CertificadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/template': {
      id: '/admin/template'
      path: '/admin/template'
      fullPath: '/admin/template'
      preLoaderRoute: typeof AdminTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiwify-webhook': {
      id: '/api/public/kiwify-webhook'
      path: '/api/public/kiwify-webhook'
      fullPath: '/api/public/kiwify-webhook'
      preLoaderRoute: typeof ApiPublicKiwifyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificadoRoute: CertificadoRoute,
  VendasscRoute: VendasscRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTemplateRoute: AdminTemplateRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
  ApiPublicKiwifyWebhookRoute: ApiPublicKiwifyWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
